Repository FindoraNetwork/platform, pull requests merged in 2021-11, with the labels that each got.

#93 v0.2.11-release
  Cargo.toml
  docs/CHANGELOG.md
  src/components/abciapp/Cargo.toml
  src/components/abciapp/src/abci/mod.rs
  src/components/abciapp/src/abci/server/callback/mod.rs
  src/components/abciapp/src/api/query_server/query_api/ledger_api.rs
  src/components/abciapp/src/api/query_server/query_api/mod.rs
  src/components/abciapp/src/api/query_server/query_api/server.rs
  src/components/finutils/Cargo.toml
  src/components/frog/Cargo.toml
  src/components/frog/build.rs
  src/components/frog/src/bins/gendtx/gendtx.rs
  src/components/frog/src/bins/genutx/genutx.rs
  src/components/frog/src/lib.rs
  src/components/wasm/Cargo.toml
  src/ledger/Cargo.toml
  src/ledger/src/data_model/mod.rs
  src/ledger/src/store/api_cache.rs
  src/ledger/src/store/mod.rs
  src/libs/bitmap/Cargo.toml
  src/libs/credentials/Cargo.toml
  src/libs/cryptohash/Cargo.toml
  src/libs/globutils/Cargo.toml
  src/libs/merkle_tree/Cargo.toml
  src/libs/sliding_set/Cargo.toml
Labels: bug, enhancement

#98 Fix delegation rewards overflow using bigint.
  src/ledger/Cargo.toml
  src/ledger/src/staking/mod.rs
Labels: bug

#106 fix internal transfer and replace todo!
  src/components/abciapp/src/abci/server/callback/mod.rs
  src/components/contracts/modules/evm/src/lib.rs
  tools/devnet/startnodes.sh
Labels: bug

#97 Change APY modifier based on v7 rate.
  src/ledger/src/store/mod.rs
Labels: enhancement

#110 Tanmay/add comments
  src/components/abciapp/src/abci/staking/mod.rs
  src/components/abciapp/src/api/query_server/query_api/ledger_api.rs
  src/components/abciapp/src/api/query_server/query_api/mod.rs
  src/components/finutils/src/api/mod.rs
  src/ledger/src/staking/cosig.rs
  src/ledger/src/staking/init/mod.rs
  src/ledger/src/staking/mod.rs
  src/ledger/src/store/mod.rs
Labels: documentation, wip

#118 feat api get_total_supply
  src/components/abciapp/src/api/query_server/query_api/mod.rs
Labels: enhancement
