Repository FindoraNetwork/platform, pull requests merged in 2021-09, with the labels that each got.

#9 Add badges
  README.md
Labels: documentation

#6 fix deliver_tx tx twice deserialize
  src/components/abciapp/Cargo.toml
  src/components/abciapp/src/abci/server/callback/mod.rs
  src/components/abciapp/src/api/submission_server/mod.rs
  src/components/contracts/modules/account/src/impls.rs
  src/components/contracts/modules/ethereum/tests/ethereum_integration.rs
  src/components/contracts/modules/evm/tests/evm_integration.rs
  src/components/contracts/modules/template/Cargo.toml
  src/components/contracts/modules/template/tests/template_integration.rs
  src/components/contracts/primitives/types/src/assemble.rs
  src/components/contracts/primitives/utils/src/lib.rs
  src/components/contracts/primitives/utils/src/tx.rs
  src/components/contracts/rpc/src/eth.rs
  src/components/finutils/Cargo.toml
  src/components/finutils/src/common/evm.rs
Labels: enhancement

#5 unfold asterisk wildcard declaration & add rpc module README.md
  src/components/contracts/rpc/README.md
  src/components/contracts/rpc/src/lib.rs
Labels: enhancement

#2 make scripts working, both devnet and debug_env
  Makefile
  tools/devnet/cleannodes.sh
  tools/devnet/confignodes.py
  tools/devnet/env.sh
  tools/devnet/resetnodes.sh
  tools/devnet/resetsingle.sh
  tools/devnet/snapshot.sh
  tools/devnet/startnetwork.sh
  tools/devnet/startnodes.sh
  tools/devnet/startsingle.sh
  tools/devnet/status.sh
  tools/devnet/stopnodes.sh
Labels: bug, enhancement

#14 optimize API layer: performance & stability
  src/components/abciapp/src/abci/mod.rs
  src/components/abciapp/src/api/query_server/query_api/ledger_api.rs
  src/components/abciapp/src/api/query_server/query_api/mod.rs
  src/components/abciapp/src/api/query_server/query_api/server.rs
  src/components/abciapp/src/api/query_server/query_api/service.rs
  src/ledger/src/data_model/mod.rs
  src/ledger/src/staking/mod.rs
  src/ledger/src/store/api_cache.rs
  src/ledger/src/store/helpers.rs
  src/ledger/src/store/mod.rs
  src/ledger/src/store/test.rs
Labels: enhancement

#16 use taged deps
  src/components/contracts/baseapp/Cargo.toml
  src/components/contracts/modules/account/Cargo.toml
  src/components/contracts/primitives/core/Cargo.toml
  src/components/contracts/primitives/storage/Cargo.toml
Labels: bug

#17 fix incorrect unbond_amount
  src/components/abciapp/src/api/query_server/query_api/ledger_api.rs
  src/ledger/src/staking/mod.rs
Labels: bug

#22 evm partial function optimization
  src/components/abciapp/src/abci/server/callback/mod.rs
  src/components/contracts/baseapp/src/app.rs
  src/components/contracts/baseapp/src/extensions.rs
  src/components/contracts/baseapp/src/lib.rs
  src/components/contracts/baseapp/src/modules.rs
  src/components/contracts/modules/account/src/impls.rs
  src/components/contracts/modules/account/src/lib.rs
  src/components/contracts/modules/account/src/tests.rs
  src/components/contracts/modules/ethereum/src/impls.rs
  src/components/contracts/modules/ethereum/src/lib.rs
  src/components/contracts/modules/ethereum/tests/ethereum_integration.rs
  src/components/contracts/modules/evm/src/impls.rs
  src/components/contracts/modules/evm/src/runtime/runner.rs
  src/components/contracts/modules/evm/src/runtime/stack.rs
  src/components/contracts/modules/evm/tests/evm_integration.rs
  src/components/contracts/modules/evm/tests/utils/erc20.rs
  src/components/contracts/modules/template/tests/template_integration.rs
  src/components/contracts/primitives/core/src/account.rs
  src/components/contracts/primitives/mocks/src/lib.rs
  src/components/contracts/primitives/traits/src/account.rs
  src/components/contracts/primitives/traits/src/base.rs
  src/components/contracts/primitives/traits/src/evm.rs
  src/components/contracts/primitives/types/src/actions/account.rs
  src/components/contracts/primitives/types/src/assemble.rs
  src/components/contracts/primitives/types/src/lib.rs
  src/components/contracts/primitives/utils/src/lib.rs
  src/components/contracts/primitives/utils/src/tx.rs
  src/components/contracts/primitives/wasm/Cargo.toml
  src/components/contracts/primitives/wasm/src/wasm.rs
  src/components/contracts/rpc/Cargo.toml
  src/components/contracts/rpc/README.md
  src/components/contracts/rpc/src/eth.rs
  src/components/contracts/rpc/src/lib.rs
  src/components/finutils/Cargo.toml
  src/components/finutils/src/bins/fn.rs
  src/components/finutils/src/common/evm.rs
  src/components/wasm/src/wasm.rs
Labels: bug, enhancement
