Repository FindoraNetwork/platform, pull requests merged in 2022-10, with the labels that each got.

#480 Add checkpoint for fixing pr366 and pr412
  src/components/abciapp/src/abci/server/callback/mod.rs
  src/components/abciapp/src/abci/staking/mod.rs
  src/components/config/src/abci/mod.rs
  src/components/contracts/modules/evm/contracts/PrismXXBridge.bytecode
Labels: bug

#669 re-implement `fn dev` based on the `chaindev` crate
  Makefile
  src/components/finutils/Cargo.toml
  src/components/finutils/src/bins/fn.rs
  src/components/finutils/src/common/dev/README.md
  src/components/finutils/src/common/dev/init.rs
  src/components/finutils/src/common/dev/mod.rs
Labels: enhancement

#670 re-implement `fn dev` based on the `chaindev` crate
  Makefile
  src/components/finutils/Cargo.toml
  src/components/finutils/src/bins/fn.rs
  src/components/finutils/src/common/dev/README.md
  src/components/finutils/src/common/dev/init.rs
  src/components/finutils/src/common/dev/mod.rs
Labels: enhancement

#682 fix `fn ddev init`
  src/components/finutils/Cargo.toml
  src/components/finutils/src/common/ddev/init.rs
  src/components/finutils/src/common/ddev/mod.rs
Labels: bug

#689 sub-PR of #688: optimize details
  src/components/abciapp/Cargo.toml
  src/components/abciapp/src/abci/mod.rs
  src/components/abciapp/src/abci/server/callback/mod.rs
  src/components/config/Cargo.toml
  src/components/config/src/findora/mod.rs
  src/ledger/src/lib.rs
Labels: documentation, enhancement
