Repository FindoraNetwork/platform, pull requests merged in 2022-09, with the labels that each got.

#504 add docs for `fn dev`, and extend functions
  Makefile
  README.md
  docs/fn_dev.md
  src/components/finutils/src/bins/fn.rs
  src/components/finutils/src/bins/fn.yml
  src/components/finutils/src/bins/stt/init/mod.rs
  src/components/finutils/src/bins/stt/stt.rs
  src/components/finutils/src/common/dev/README.md
  src/components/finutils/src/common/dev/init.rs
  src/components/finutils/src/common/dev/mod.rs
  src/ledger/src/staking/mod.rs
Labels: enhancement

#507 cherry-pick #504
  Makefile
  README.md
  docs/fn_dev.md
  src/components/finutils/src/bins/fn.rs
  src/components/finutils/src/bins/fn.yml
  src/components/finutils/src/bins/stt/init/mod.rs
  src/components/finutils/src/bins/stt/stt.rs
  src/components/finutils/src/common/dev/README.md
  src/components/finutils/src/common/dev/init.rs
  src/components/finutils/src/common/dev/mod.rs
  src/ledger/src/staking/mod.rs
Labels: documentation, enhancement

#512 tuning some details of `fn dev`
  src/components/finutils/src/bins/fn.rs
  src/components/finutils/src/bins/fn.yml
  src/components/finutils/src/common/dev/README.md
  src/components/finutils/src/common/dev/mod.rs
Labels: documentation, enhancement

#514 tuning some details of `fn dev` (#512)
  src/components/finutils/src/bins/fn.rs
  src/components/finutils/src/bins/fn.yml
  src/components/finutils/src/common/dev/README.md
  src/components/finutils/src/common/dev/mod.rs
Labels: documentation, enhancement

#515 fix ports checker issue in `fn dev create`
  src/components/finutils/src/common/dev/mod.rs
Labels: bug

#421 Modify the validator's validator line to 100
  src/components/abciapp/src/abci/staking/mod.rs
  src/components/config/src/abci/mod.rs
Labels: enhancement

#502 Fix `check_tx` bug that not check prism tx
  src/ledger/src/data_model/mod.rs
Labels: bug

#505 Add new field `pubkey_sign_map` for `Transaction` struct
  src/components/finutils/src/common/evm.rs
  src/components/finutils/src/common/mod.rs
  src/components/finutils/src/common/utils.rs
  src/components/finutils/src/txn_builder/mod.rs
  src/components/wasm/src/wasm.rs
  src/ledger/src/data_model/mod.rs
  src/ledger/src/store/utils.rs
Labels: enhancement

#536 add dependabot
  .github/dependabot.yml
Labels: enhancement

#566 Fix converter
  src/components/contracts/baseapp/src/modules.rs
  src/ledger/src/converter/mod.rs
Labels: bug

#567 filter out the node itself when setting persistent peers
  src/components/finutils/src/common/dev/mod.rs
Labels: enhancement

#569 make CHANGELOG compatible with github detector
  CHANGELOG.md
  README.md
Labels: documentation
