Repository FindoraNetwork/platform, pull requests merged in 2022-08, with the labels that each got.

#413 fix logic bug for asset type code prefix
  src/components/config/src/abci/mod.rs
  src/ledger/src/data_model/effects.rs
  src/ledger/src/store/mod.rs
  src/ledger/src/store/test.rs
Labels: bug

#415 Modify the height of the new function in checkpoint
  src/components/config/src/abci/mod.rs
Labels: bug

#445 fmt code; ignore checkpoint files(generated by tests)
  .gitignore
  src/components/contracts/modules/ethereum/src/impls.rs
  src/components/contracts/primitives/core/src/context.rs
  src/ledger/src/data_model/effects.rs
  src/libs/merkle_tree/src/lib.rs
Labels: enhancement

#468 fix api for `get_created_assets`
  src/components/abciapp/src/api/query_server/query_api/mod.rs
  src/components/finutils/src/common/mod.rs
  src/components/finutils/src/common/utils.rs
Labels: bug

#430 fix undelegation missing reward.
  src/components/abciapp/src/abci/server/callback/mod.rs
  src/components/abciapp/src/abci/staking/mod.rs
  src/components/config/src/abci/mod.rs
  src/ledger/src/staking/mod.rs
Labels: bug

#473 fix compilation on MacOS and `make join_qa0N`
  .gitignore
  Makefile
  src/components/abciapp/src/api/query_server/query_api/mod.rs
  src/components/config/src/abci/mod.rs
  src/components/config/src/findora/mod.rs
  tools/download_tendermint.sh
  tools/fmt.sh
  tools/node_init.sh
Labels: bug, enhancement

#476 advanced managements of local clusters（DevNet）
  Makefile
  src/components/config/src/abci/mod.rs
  src/components/contracts/rpc/Cargo.toml
  src/components/finutils/Cargo.toml
  src/components/finutils/src/bins/fn.rs
  src/components/finutils/src/bins/fn.yml
  src/components/finutils/src/common/dev/README.md
  src/components/finutils/src/common/dev/init.rs
  src/components/finutils/src/common/dev/mod.rs
  src/components/finutils/src/common/mod.rs
  src/components/finutils/src/common/utils.rs
  src/ledger/Cargo.toml
  src/ledger/src/data_model/mod.rs
  src/ledger/src/staking/mod.rs
Labels: enhancement

#485 Fix the implementation logic of `check_tx`
  src/components/config/src/abci/mod.rs
  src/ledger/src/data_model/mod.rs
  src/libs/sliding_set/src/lib.rs
Labels: bug

#497 fix fn dev
  src/components/finutils/src/common/dev/init.rs
  src/components/finutils/src/common/dev/mod.rs
  src/ledger/src/staking/mod.rs
Labels: bug
