Repository FindoraNetwork/platform, pull requests merged in 2023-03, with the labels that each got.

#861 add rls build to makefile
  Makefile
Labels: enhancement

#864 make the `develop` branch compatible with current mainnet
  container/docker-entrypoint-findorad.sh
  src/components/config/src/abci/mod.rs
  src/components/finutils/src/bins/cfg_generator.rs
  src/components/finutils/src/common/mod.rs
  src/libs/merkle_tree/src/lib.rs
  tools/benchutils/bench.sh
  tools/fn_check.sh
  tools/node_init.sh
Labels: bug, enhancement

#865 fix `make bench_xx`
  Makefile
  src/components/config/src/abci/mod.rs
  tools/benchutils/bench.sh
Labels: bug

#867 fix wrong logic in crtlc handler
  src/components/abciapp/src/abci/server/callback/mod.rs
  src/components/abciapp/src/bins/abcid.rs
  src/components/config/src/abci/mod.rs
  src/components/config/src/lib.rs
Labels: bug

#869 optimize code details in the abcid process startup logic
  src/components/abciapp/src/abci/mod.rs
  src/components/abciapp/src/abci/server/callback/mod.rs
Labels: enhancement

#868 fix check_signatures_num
  src/components/abciapp/src/abci/server/callback/mod.rs
Labels: bug

#876 add contributors section in README
  README.md
Labels: documentation

#883 fix clippy
  src/components/config/src/findora/mod.rs
  src/components/contracts/primitives/rpc-core/src/types/block_number.rs
  src/components/contracts/primitives/rpc-core/src/types/pubsub.rs
  src/ledger/src/data_model/mod.rs
  src/ledger/src/staking/mod.rs
Labels: bug
